action_id: trunk-upgrade-available
date: 2024-02-15 12:56:39
run: trunk upgrade --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 1h
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1708001799
full_timestamp:
  nanos: 71584000
  seconds: 1708001799
trunk_version: 1.19.0
